name: my own tests

on: [push]

jobs:
  start-eslint:
    runs-on: ubuntu-latest 
    steps:
      - name: git clone
        uses: actions/checkout@v1
        
      - name: node install
        uses: actions/setup-node@v2.1.2
        
      - name: npm install
        run: make install
        
      - name: run eslint
        run: make lint
        
      - name: run tests
        run: make test
        
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
